feat: add badge
bnb-chain/mind-marketplace-contract pull request #2
Opened 2023-10-31 08:44 UTC by pythonberg1997

### Description

This pr is to add a new ERC1155 badge contract

### Changes

Notable changes:
* add ERC1155 badge contract

2023-10-31 10:26 UTC, unclezoro approved these changes

2023-11-13 07:48 UTC, forcodedancing approved these changes

2023-11-14 07:16 UTC, forcodedancing requested changes
* confirmed with Alina, need 4 badges
* mainnet deploy does not contain this pr
* need upgrade

2024-12-31 03:59 UTC, ruojunm commented
close it for now, as it will not be maintained anymore. 
We can reopen it in case we need it in the future.

2024-12-31 03:59 UTC, closed without merging